# Generated by Django 4.1.1 on 2022-11-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkpreset',
            name='description',
            field=models.TextField(default='TODO: ADD DESCRIPTION', max_length=75),
        ),
        migrations.AddField(
            model_name='drinkpreset',
            name='image',
            field=models.URLField(default='/menu/images/missing'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='buy_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='milkingredient',
            name='buy_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
