# Generated by Django 4.0.2 on 2022-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=0),
        ),
    ]
