# Generated by Django 4.0.2 on 2022-10-26 19:01

from django.db import migrations, models
import menu.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cart',
            field=models.JSONField(default=menu.utils.get_empty_order),
        ),
    ]
