# Generated by Django 4.0.2 on 2022-10-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('edit_employees', 'Can add, remove, and pay employees'), ('handle_orders', 'Can view employee pages'), ('order_inventory', 'Can order additional inventory'), ('edit_menu', 'Can add or remove menu items')]},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
