# Generated by Django 4.0.2 on 2022-11-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
