# Generated by Django 4.0.2 on 2022-11-02 05:24

from django.db import migrations, models

from account.models import UserAccount


class Migration(migrations.Migration):
    def add_admin():
        admin = UserAccount.objects.create_user("admin@gmail.com", "admin@gmail.com", "password")
        admin.first_name = "admin"
        admin.last_name = " "
        admin.setManager()
        admin.save()

    dependencies = [
        ('account', '0005_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.RunPython(add_admin)
        
    ]
