# Generated by Django 4.0.2 on 2022-11-02 18:02

from django.db import migrations, models
from account.models import UserAccount

class Migration(migrations.Migration):
    def add_admin(apps, schema_editor):
        admin = UserAccount.objects.create_user("admin", "admin@gmail.com", "password")
        admin.first_name = "admin"
        admin.last_name = " "
        admin.setManager()
        admin.save()

    dependencies = [
        ('account', '0006_alter_useraccount_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_admin),
    ]
