# Generated by Django 4.0.2 on 2022-11-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useraccount_employee_useraccount_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
