# Generated by Django 4.0.2 on 2022-11-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useraccount_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
