# Generated by Django 3.2.8 on 2022-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_useraccount_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='store',
            field=models.BooleanField(default=False),
        ),
    ]
