# Generated by Django 4.0.2 on 2022-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_useraccount_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cart',
            field=models.JSONField(default={'items': []}),
        ),
    ]
